language: node_js
node_js:
    - 9
cache:
    yarn: true
    directories:
        - node_modules
        - packages/create-react-app/node_modules
        - packages/react-scripts/node_modules
script:
    - yarn test-ci
    - yarn build
