const abbrevations = {
  '1mose': '1 Mos',
  '2mose': '2 Mos',
  '3mose': '3 Mos',
  '4mose': '4 Mos',
  '5mose': '5 Mos',
  josua: 'Jos',
  dommer: 'Dom',
  rut: 'Rut',
  '1samuel': '1 Sam',
  '2samuel': '2 Sam',
  '1konge': '1 Kong',
  '2konge': '2 Kong',
  '1kroen': '1 Krøn',
  '2kroen': '2 Krøn',
  ezra: 'Ezra',
  nehemias: 'Neh',
  ester: 'Est',
  job: 'Job',
  salme: 'Sl',
  ordsprog: 'Ordsp',
  praed: 'Præd',
  hoej: 'Højs',
  esajas: 'Es',
  jeremias: 'Jer',
  klage: 'Klages',
  ezekiel: 'Ez',
  daniel: 'Dan',
  hoseas: 'Hos',
  joel: 'Joel',
  amos: 'Am',
  obadias: 'Obad',
  jonas: 'Jon',
  mikas: 'Mika',
  nahum: 'Nah',
  habakkuk: 'Hab',
  zefanias: 'Zef',
  haggaj: 'Hagg',
  zakarias: 'Zak',
  malakias: 'Mal',
  matt: 'Matt',
  markus: 'Mark',
  lukas: 'Luk',
  johannes: 'Joh',
  apostlene: 'Ap.G',
  rom: 'Rom',
  '1korint': '1 Kor',
  '2korint': '2 Kor',
  galaterne: 'Gal',
  efeserne: 'Ef',
  filipperne: 'Fil',
  kolossen: 'Kol',
  '1tessa': '1 Tess',
  '2tessa': '2 Tess',
  '1timoteus': '1 Tim',
  '2timoteus': '2 Tim',
  titus: 'Tit',
  filemon: 'Filem',
  hebrae: 'Hebr',
  jakob: 'Jak',
  '1peter': '1 Pet',
  '2peter': '2 Pet',
  '1johannes': '1 Joh',
  '2johannes': '2 Joh',
  '3johannes': '3 Joh',
  judas: 'Jud',
  aabenbaringen: 'Åb',
};

module.exports.abbrevations = abbrevations;
