const placeReplacementsByLang = {
  en: [
    ['Christianborg Slot', 'Christiansborg Palace'],
    ['Christiansborg Slot', 'Christiansborg Palace'],
    ['Charlottenlund Slot', 'Charlottenlund Palace'],
    ['Frederiksborg Slot', 'Frederiksborg Castle'],
    ['Københavns Slot', 'Copenhagen Castle'],
    ['Amalienborg Slot', 'Amalienborg Palace'],
    ['Gottorp Slot', 'Gottorp Castle'],
    ['Nyborg Slot', 'Nyborg Castle'],
    ['Kalundborg Slot', 'Kalundborg Castle'],
    ['Aalborghus Slot', 'Aalborghus Castle'],
    ['Hirschholm Slot', 'Hirschholm Palace'],
    ['Rosenborg Slot', 'Rosenborg Castle'],
    ['Sorgenfri Slot', 'Sorgenfri Palace'],
    ['Skt. Thomas', 'St. Thomas'],
    ['Skt. Petersborg', 'St. Petersburg'],
    ['Kbh.', 'Copenhagen'],
    ['København', 'Copenhagen'],
    ['Hamborg', 'Hamburg'],
    ['Helsingør', 'Elsinore'],
    ['Firenze', 'Florence'],
    ['Venedig', 'Venice'],
    ['Rom', 'Rome'],
    ['Milano', 'Milan'],
    ['Napoli', 'Naples'],
    ['Lissabon', 'Lisbon'],
    ['Prag', 'Prague'],
    ['Wien', 'Vienna'],
    ['Rendsborg', 'Rendsburg'],
    ['Braunschweig', 'Brunswick'],
    ['Trondhjem', 'Trondheim'],
    ['Göteborg', 'Gothenburg'],
    ['Malmø', 'Malmo'],
    ['Konstantinopel', 'Constantinople'],
    ['Turino', 'Turin'],
    ['Nuremburg', 'Nuremberg'],
    ['Kristiania', 'Christiania'],
    ['Århus', 'Aarhus'],
    ['Slesvig by', 'Schleswig town'],
    ['Slesvig', 'Schleswig'],
    ['Skaane', 'Scania'],
    ['Skåne', 'Scania'],
    ['Sjælland', 'Zealand'],
    ['Jylland', 'Jutland'],
    ['Fyn', 'Funen'],
    ['Møn', 'Moen'],
    ['Dansk Vestindien', 'Danish West Indies'],
    ['Rusland', 'Russia'],
    ['Tyskland', 'Germany'],
    ['Frankrig', 'France'],
    ['Sverige', 'Sweden'],
    ['Norge', 'Norway'],
    ['Grækenland', 'Greece'],
    ['Irland', 'Ireland'],
    ['Skotland', 'Scotland'],
    ['Østrig-Ungarn', 'Austria-Hungary'],
    ['Østrig', 'Austria'],
    ['Ungarn', 'Hungary'],
    ['Tjekkiet', 'Czechia'],
    ['Schweiz', 'Switzerland'],
    ['Persien', 'Persia'],
    ['Indien', 'India'],
    ['Polen', 'Poland'],
    ['Rumænien', 'Romania'],
    ['Slovenien', 'Slovenia'],
    ['Kina', 'China'],
    ['Kirchenstaat', 'Papal States'],
    ['Italien', 'Italy'],
    ['Spanien', 'Spain'],
    ['Holland', 'the Netherlands'],
    ['Nederlandene', 'the Netherlands'],
    [' ved ', ' near '],
    [' nær ', ' near '],
    ['(nu ', '(now '],
    ['øen ', 'the island of '],
    ['skibsforlis på vej hjem fra ', 'shipwreck on the way home from '],
    ['nuværende ', 'present-day '],
    ['tidl. ', 'formerly '],
    ['formodentligt', 'presumably'],
    ['sandsynligvis', 'probably'],
  ],
};

const translatePlace = (place, lang) => {
  return (placeReplacementsByLang[lang] || []).reduce(
    (translated, [from, to]) => translated.replaceAll(from, to),
    place
  );
};

module.exports = {
  translatePlace,
};
